# Generated by Django 3.1.14 on 2022-03-06 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AddDepartment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('departmentName', models.CharField(max_length=191, null=True)),
                ('basicPay', models.BigIntegerField(blank=True, null=True)),
                ('travelAllowance', models.BigIntegerField(blank=True, null=True)),
                ('medicalAllowance', models.BigIntegerField(blank=True, null=True)),
                ('washingAllowance', models.BigIntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
            ],
        ),
    ]
