# Generated by Django 3.1.14 on 2022-03-06 11:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('esaapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AddEmployee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullName', models.CharField(blank=True, max_length=191, null=True)),
                ('address', models.CharField(blank=True, max_length=200, null=True)),
                ('permanentAddr', models.CharField(blank=True, max_length=250, null=True)),
                ('city', models.CharField(blank=True, max_length=150, null=True)),
                ('pincode', models.IntegerField(blank=True, null=True)),
                ('mobile', models.IntegerField(blank=True, null=True)),
                ('bankAccount', models.BigIntegerField(blank=True, null=True)),
                ('email', models.EmailField(max_length=255)),
                ('pasword', models.CharField(max_length=50)),
                ('department', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='esaapp.adddepartment')),
            ],
        ),
    ]
