# Generated by Django 3.1.14 on 2022-03-21 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('esaapp', '0002_addemployee'),
    ]

    operations = [
        migrations.AddField(
            model_name='addemployee',
            name='adhaar',
            field=models.ImageField(blank=True, null=True, upload_to='uploads/'),
        ),
        migrations.AddField(
            model_name='addemployee',
            name='pancard',
            field=models.ImageField(blank=True, null=True, upload_to='uploads/'),
        ),
        migrations.AddField(
            model_name='addemployee',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='uploads/'),
        ),
        migrations.AddField(
            model_name='addemployee',
            name='state',
            field=models.CharField(blank=True, max_length=191, null=True),
        ),
        migrations.AlterField(
            model_name='addemployee',
            name='department',
            field=models.CharField(blank=True, max_length=191, null=True),
        ),
        migrations.AlterField(
            model_name='addemployee',
            name='mobile',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='addemployee',
            name='pincode',
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
