# Generated by Django 3.1.14 on 2022-03-21 15:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('esaapp', '0003_auto_20220321_2047'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='addemployee',
            name='adhaar',
        ),
        migrations.RemoveField(
            model_name='addemployee',
            name='pancard',
        ),
        migrations.RemoveField(
            model_name='addemployee',
            name='photo',
        ),
    ]
