# Generated by Django 3.2.12 on 2022-03-18 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('esaapp', '0003_salaryreport'),
    ]

    operations = [
        migrations.AddField(
            model_name='salaryreport',
            name='total',
            field=models.BigIntegerField(blank=True, max_length=200, null=True),
        ),
    ]
