# Generated by Django 3.2.12 on 2022-03-19 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('esaapp', '0004_salaryreport_total'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salaryreport',
            name='bankAccount',
            field=models.BigIntegerField(blank=True, max_length=400, null=True),
        ),
        migrations.AlterField(
            model_name='salaryreport',
            name='total',
            field=models.BigIntegerField(blank=True, max_length=500, null=True),
        ),
    ]
