# Generated by Django 3.2.12 on 2022-03-19 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('esaapp', '0005_auto_20220319_1919'),
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(blank=True, max_length=191, null=True)),
                ('Account', models.BigIntegerField(blank=True, max_length=400, null=True)),
                ('TA', models.IntegerField(blank=True, max_length=100, null=True)),
                ('MA', models.IntegerField(blank=True, max_length=100, null=True)),
                ('WA', models.IntegerField(blank=True, max_length=100, null=True)),
                ('Total', models.BigIntegerField(blank=True, max_length=500, null=True)),
            ],
        ),
        migrations.DeleteModel(
            name='SalaryReport',
        ),
    ]
