# Generated by Django 3.2.12 on 2022-03-20 04:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('esaapp', '0007_auto_20220319_2103'),
    ]

    operations = [
        migrations.AddField(
            model_name='salaryreport',
            name='date',
            field=models.DateField(null=True),
        ),
    ]
