# Generated by Django 3.2.12 on 2022-03-21 02:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('esaapp', '0008_salaryreport_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='salaryreport',
            name='date',
        ),
        migrations.AddField(
            model_name='salaryreport',
            name='month',
            field=models.CharField(blank=True, max_length=191, null=True),
        ),
    ]
