# Generated by Django 3.2.12 on 2022-03-21 03:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('esaapp', '0009_auto_20220321_0823'),
    ]

    operations = [
        migrations.AddField(
            model_name='salaryreport',
            name='pic',
            field=models.ImageField(default='', upload_to='esaapp/salary_report'),
        ),
        migrations.AlterField(
            model_name='salaryreport',
            name='month',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
