# Generated by Django 3.2.12 on 2022-03-21 03:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('esaapp', '0010_auto_20220321_0849'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salaryreport',
            name='pic',
            field=models.ImageField(default='', upload_to='salary_report'),
        ),
    ]
