# Generated by Django 3.2.12 on 2022-03-21 03:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('esaapp', '0011_alter_salaryreport_pic'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='salaryreport',
            name='pic',
        ),
    ]
