# Generated by Django 3.2.12 on 2022-03-24 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('esaapp', '0013_employeedetail'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeedetail',
            name='firstname',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='employeedetail',
            name='lastname',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
